/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Entity.ErrorsAndSuccesses;
import Entity.ticket_generado;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Generar_ticket extends javax.swing.JPanel implements Printable{
    String ubicacion;
    ErrorsAndSuccesses es = new ErrorsAndSuccesses();
    public Generar_ticket(String ubicacion) {
        initComponents();
        es.setUbicacion(ubicacion);
        ticket_generado tg = new ticket_generado();
        Empresa.setText(tg.getNombre_empresa());
        S_a_c_v.setText(tg.getS_a_c_v());
        muniest.setText(tg.getMunicipio()+", "+ tg.getEstado());
        rfc.setText(tg.getRfc());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        S_a_c_v = new javax.swing.JLabel();
        Empresa = new javax.swing.JLabel();
        muniest = new javax.swing.JLabel();
        rfc = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1022, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(1022, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("----------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel2.setText("----------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jLabel3.setText("----------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setText("----------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jLabel5.setText("----------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setText("----------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel7.setText("DATOS DEL CLIENTE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        jLabel8.setText("DATOS DEL CLIENTE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel9.setText("----------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, -1, -1));
        jPanel1.add(S_a_c_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 180, 20));
        jPanel1.add(Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 20));
        jPanel1.add(muniest, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 180, 20));
        jPanel1.add(rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Thread() {
            public void run() {
                imprimir();         
            }
        }.start();

    }//GEN-LAST:event_jButton1ActionPerformed
    public void imprimir() {
        try {
            PrinterJob g = PrinterJob.getPrinterJob();
            g.setPrintable(this);
            boolean gl = g.printDialog();
            if (gl) {
                g.print();
            }
            JOptionPane.showMessageDialog(this, "Exito", "Impresion", JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException | PrinterException e) {
            JOptionPane.showMessageDialog(this, "Error al imprimir", "Impresion", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Empresa;
    private javax.swing.JLabel S_a_c_v;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel muniest;
    private javax.swing.JLabel rfc;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
